### ISSUE TITLE
S3 Images return 403

### ISSUE THREAD

**Issue by mitchmalone** [alvis/gatsby-source-notion#8]
I suspect I am perhaps doing something wrong here, but when I include Cover images from S3 I get a bunch of 403 console errors.

You can view my [WIP here](https://develop--spiffy-cannoli-bf18cd.netlify.app) for an example of what's happennig.

**Comment by mitchmalone** [comment]
Note: This seems to work occasionally after a rebuild and then stops. Not sure what this might mean.

**Comment by alvis** [comment]
Hi @mitchmalone. I believe the 403 response is caused by your image being hosted by Notion rather than somewhere else.
It's a limitation of Notion API that if you upload an image on Notion, the returned link via Notion API is only valid for 1 hour.

The only workaround is to use an externally hosted image as your cover image. You can use other public hosting like Dropbox and set your cover image by the public URL on Notion.
